yaml file updated-2

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -7,13 +7,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       -name: Say hello
-      run: echo "Hello,world"
+        run: echo "Hello,world"
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
       -name: Failed step
-      run: |
-        echo: "I will fail"
-        exit 1
+        run: |
+          echo: "I will fail"
+          exit 1
       -name: Say goodbye
-      run: echo "Goodbye"
+        run: echo "Goodbye"
